const express=require('express')
const userMiddleware=require('../middleware/userMiddleware')
const {profileImageUploader,usersImagesUploader}=require('../multerUploaders')
const userController=require('../controllers/userController')
const router=express.Router()
router.post('/create-account',userController.createAccount)
router.get('/login',userController.login)
router.get('/validate-token',userController.validateToken)
router.get('/request-code',userController.createVerificationCode)
router.get('/verify-code',userController.verifyCode)
router.post('/profile-image',userMiddleware.profileSetupMiddleware,profileImageUploader.single('image'),userController.setProfileImage)
router.get('/profile-image',userController.sendProfileImage)
router.patch('/modify-profile',userMiddleware.profileModificationMiddleware,usersImagesUploader.array('files',8),userController.modifyProfile)
router.put('/change-password',userController.changePassword)
router.put('/change-password',userController.changePassword)
router.put('/change-email',userController.changeEmail)
router.get('/confirm-old-email-change',userController.receiveFirstConfirmation)
router.get('/confirm-new-email-change',userController.receiveSecondConfirmation)
router.get('/get-users-profile',userController.getUsersProfile)
module.exports=router